"""The published SDK surface: one dotted id per REGIONAL route.

This is the document `clients/` and `mcp/tools.json` are generated from, so
every name here reaches a tenant. See ``api.core.sdk_surface`` for what the dots
mean and why a route missing from this map fails at import.

Control's 17 operations are not here — they live in ``api.control.sdk_surface``
and are published nowhere. Checked route by route, a tenant integrating never
needs them: sign-in and the org switcher are browser redirects and a cookie,
tokens are bootstrap-shaped (you need a token to create a token), and members
and invites are already a settled product decision to keep in the dashboard.
Credits are the case that would have broken this and does not — the balance is
regional, so it is here.

``auth.me`` is the one debatable removal, and it goes: keeping it is what would
make the published client span two planes. If it is ever asked for, the answer is
a lightweight identity echo HERE, answered from the auth context this app already
fetches on every request.
"""

from __future__ import annotations

from api.core.sdk_surface import SdkSurface

SDK_SURFACE: dict[str, str] = {
    "health": "health",
    "list_agents": "agents.list",
    "create_agent": "agents.create",
    "get_agent": "agents.get",
    "update_agent": "agents.update",
    "delete_agent": "agents.delete",
    "publish_agent": "agents.publish",
    "validate_agent": "agents.validate",
    "get_agent_version": "agents.versions.get",
    "rollback_agent_version": "agents.versions.rollback",
    "list_tools": "tools.list",
    "create_tool": "tools.create",
    "get_tool": "tools.get",
    "patch_tool": "tools.update",
    "delete_tool": "tools.delete",
    "publish_tool": "tools.publish",
    "validate_tool": "tools.validate",
    "run_tool": "tools.run",
    "get_tool_version": "tools.versions.get",
    "rollback_tool_version": "tools.versions.rollback",
    "list_tasks": "tasks.list",
    "create_task": "tasks.create",
    "get_task": "tasks.get",
    "update_task": "tasks.update",
    "delete_task": "tasks.delete",
    "validate_task": "tasks.validate",
    "publish_task": "tasks.publish",
    "get_task_version": "tasks.versions.get",
    "rollback_task_version": "tasks.versions.rollback",
    "list_task_runs": "tasks.runs.list",
    "run_task": "tasks.runs.create",
    "get_task_run": "tasks.runs.get",
    "list_calls": "calls.list",
    "get_call": "calls.get",
    "delete_call": "calls.delete",
    "call_stats": "calls.stats",
    "calls_token": "calls.token",
    "create_outbound_call": "calls.outbound",
    "get_call_recording": "calls.recording.get",
    "delete_call_recording": "calls.recording.delete",
    "get_call_screen_recording": "calls.screenRecording.get",
    "preview_call_analysis": "calls.analysis.preview",
    "backfill_call_analysis": "calls.analysis.backfill",
    "list_call_batches": "calls.batches.list",
    "create_call_batch": "calls.batches.create",
    "get_call_batch": "calls.batches.get",
    "patch_call_batch": "calls.batches.update",
    "pause_call_batch": "calls.batches.pause",
    "resume_call_batch": "calls.batches.resume",
    "cancel_call_batch": "calls.batches.cancel",
    "delete_call_batch": "calls.batches.delete",
    "list_call_batch_recipients": "calls.batches.recipients.list",
    "add_call_batch_recipients": "calls.batches.recipients.add",
    "list_conversations": "conversations.list",
    "get_conversation": "conversations.get",
    "patch_conversation": "conversations.update",
    "conversation_event_stream": "conversations.events",
    "get_conversation_snapshot": "conversations.snapshot",
    "list_conversation_trace": "conversations.trace",
    "list_conversation_items": "conversations.items.list",
    "list_conversation_sessions": "conversations.sessions.list",
    "list_chats": "chats.list",
    "create_chat": "chats.create",
    "get_chat": "chats.get",
    "get_chat_detail": "chats.detail",
    "rerun_chat_analysis": "chats.analysis.rerun",
    "preview_chat_analysis": "chats.analysis.preview",
    "list_chat_items": "chats.items.list",
    "create_chat_message": "chats.messages.create",
    "end_chat": "chats.end",
    "create_chat_token": "chats.tokens.create",
    "delete_chat": "chats.delete",
    "agent_copilot_stream": "copilot.agents.stream",
    "agent_copilot_send_message": "copilot.agents.send",
    "tool_copilot_stream": "copilot.tools.stream",
    "tool_copilot_send_message": "copilot.tools.send",
    "task_copilot_stream": "copilot.tasks.stream",
    "task_copilot_send_message": "copilot.tasks.send",
    "list_email_senders": "email.senders.list",
    "list_email_batches": "email.batches.list",
    "create_email_batch": "email.batches.create",
    "get_email_batch": "email.batches.get",
    "patch_email_batch": "email.batches.update",
    "pause_email_batch": "email.batches.pause",
    "resume_email_batch": "email.batches.resume",
    "cancel_email_batch": "email.batches.cancel",
    "delete_email_batch": "email.batches.delete",
    "list_email_batch_recipients": "email.batches.recipients.list",
    "add_email_batch_recipients": "email.batches.recipients.add",
    "patch_email_batch_recipient": "email.batches.recipients.update",
    "skip_email_batch_recipients": "email.batches.recipients.skip",
    "restore_email_batch_recipients": "email.batches.recipients.restore",
    "redraft_email_batch_recipients": "email.batches.recipients.redraft",
    "create_email_send": "email.batches.sends.create",
    "list_email_sends": "email.batches.sends.list",
    "get_email_send": "email.batches.sends.get",
    "patch_email_send": "email.batches.sends.update",
    "pause_email_send": "email.batches.sends.pause",
    "resume_email_send": "email.batches.sends.resume",
    "cancel_email_send": "email.batches.sends.cancel",
    "list_whatsapp_templates": "whatsapp.templates.list",
    "list_twilio_whatsapp_senders": "whatsapp.twilioSenders.list",
    "list_whatsapp_batches": "whatsapp.batches.list",
    "create_whatsapp_batch": "whatsapp.batches.create",
    "get_whatsapp_batch": "whatsapp.batches.get",
    "patch_whatsapp_batch": "whatsapp.batches.update",
    "send_whatsapp_batch": "whatsapp.batches.send",
    "pause_whatsapp_batch": "whatsapp.batches.pause",
    "resume_whatsapp_batch": "whatsapp.batches.resume",
    "cancel_whatsapp_batch": "whatsapp.batches.cancel",
    "delete_whatsapp_batch": "whatsapp.batches.delete",
    "list_whatsapp_batch_recipients": "whatsapp.batches.recipients.list",
    "add_whatsapp_batch_recipients": "whatsapp.batches.recipients.add",
    "patch_whatsapp_batch_recipient": "whatsapp.batches.recipients.update",
    "skip_whatsapp_batch_recipients": "whatsapp.batches.recipients.skip",
    "restore_whatsapp_batch_recipients": "whatsapp.batches.recipients.restore",
    "list_integrations": "integrations.list",
    "create_integration": "integrations.create",
    "get_integration": "integrations.get",
    "patch_integration": "integrations.update",
    "delete_integration": "integrations.delete",
    "integration_catalog": "integrations.catalog",
    "list_integration_mcp_tools": "integrations.mcpTools.list",
    "list_integration_triggers": "integrations.triggers.list",
    "create_integration_trigger": "integrations.triggers.create",
    "patch_integration_trigger": "integrations.triggers.update",
    "delete_integration_trigger": "integrations.triggers.delete",
    "list_faqs": "faqs.list",
    "create_faq": "faqs.create",
    "get_faq": "faqs.get",
    "update_faq": "faqs.update",
    "delete_faq": "faqs.delete",
    "create_faq_entries": "faqs.entries.create",
    "update_faq_entry": "faqs.entries.update",
    "delete_faq_entry": "faqs.entries.delete",
    "list_telephony_providers": "telephony.providers.list",
    "list_telephony_accounts": "telephony.accounts.list",
    "create_telephony_account": "telephony.accounts.create",
    "get_telephony_account": "telephony.accounts.get",
    "patch_telephony_account": "telephony.accounts.update",
    "delete_telephony_account": "telephony.accounts.delete",
    "provision_telephony_account": "telephony.accounts.provision",
    "list_remote_numbers": "telephony.accounts.remoteNumbers",
    "list_phone_numbers": "telephony.phoneNumbers.list",
    "import_phone_numbers": "telephony.phoneNumbers.import",
    "get_phone_number": "telephony.phoneNumbers.get",
    "patch_phone_number": "telephony.phoneNumbers.update",
    "assign_phone_number": "telephony.phoneNumbers.assign",
    "unassign_phone_number": "telephony.phoneNumbers.unassign",
    "provision_phone_number": "telephony.phoneNumbers.provision",
    "list_stream_connections": "telephony.streams.list",
    "create_stream_connection": "telephony.streams.create",
    "get_stream_connection": "telephony.streams.get",
    "patch_stream_connection": "telephony.streams.update",
    "delete_stream_connection": "telephony.streams.delete",
    "get_catalog": "catalog.get",
    "search_models": "catalog.models.search",
    "list_model_hosts": "catalog.models.hosts",
    "catalog_voices": "catalog.voices.list",
    "catalog_avatars": "catalog.avatars.list",
    "add_elevenlabs_voice": "catalog.voices.elevenlabs.add",
    "elevenlabs_voice_settings": "catalog.voices.elevenlabs.settings",
    "get_observability": "observability.get",
    "describe_schema": "schemas.get",
    "describe_function": "schemas.functions.get",
    "list_secrets": "secrets.list",
    "create_secret": "secrets.create",
    "delete_secret": "secrets.delete",
    "list_provider_keys": "providerKeys.list",
    "set_provider_key": "providerKeys.set",
    "delete_provider_key": "providerKeys.delete",
    "list_webhooks": "webhooks.list",
    "create_webhook": "webhooks.create",
    "patch_webhook": "webhooks.update",
    "delete_webhook": "webhooks.delete",
    "test_webhook": "webhooks.test",
    "rotate_webhook_secret": "webhooks.rotateSecret",
    "webhook_deliveries": "webhooks.deliveries",
    "event_types": "webhooks.eventTypes",
    "get_credits": "billing.credits.get",
    "list_credit_ledger": "billing.credits.ledger",
    "create_credit_checkout": "billing.credits.checkout",
}

SURFACE = SdkSurface("dataplane", SDK_SURFACE)
