#!/usr/bin/env python3
"""Generate the Python SDK's API surface from ``openapi/openapi.json``.

``src/talqing/gen`` is checked in and never edited by hand. Regenerate with

    python clients/python/generate.py

after re-running ``openapi/export.py``; ``--check`` asserts the tree on disk is
still what the document generates instead of writing it.

The shape is the one ``backend/api/sdk_surface.py`` declares. A dotted operation
id is a path through the client, so ``agents.versions.rollback`` is
``client.agents.versions.rollback(...)`` here and the same call in the
TypeScript SDK. Each part is snake_cased on the way in — ``telephony.phoneNumbers``
becomes ``client.telephony.phone_numbers`` — because that is the same name
written the way Python writes names.

Three rules decide the rest:

- **A schema becomes a TypedDict, and a response is the decoded JSON.** Nothing
  is validated or coerced on arrival, so the SDK cannot reject a payload the API
  considers valid, and ``httpx`` stays the only runtime dependency.
- **A request body is expanded into keyword arguments.** No body property
  collides with a path or query parameter anywhere in the document — the
  generator asserts it — so ``agents.create(name=..., config=...)`` is
  unambiguous.
- **What the caller does not pass is not sent.** Optional arguments default to
  ``OMIT``, never to the server's own default, because ``null`` is a real value
  on several PATCH bodies (``orgs.update(retention_days=None)`` means "keep
  everything forever") and has to stay distinguishable from "leave it alone".
"""

from __future__ import annotations

import argparse
import json
import keyword
import re
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[2]
SPEC = REPO / "openapi" / "openapi.json"
OUT = Path(__file__).resolve().parent / "src" / "talqing" / "gen"

HTTP_METHODS = ("get", "post", "put", "patch", "delete")

BANNER = (
    "# Generated by clients/python/generate.py from openapi/openapi.json.\n"
    "# Do not edit: run `python clients/python/generate.py` instead.\n"
)

# The named vocabularies the document spells inline.
#
# Pydantic renders a `Literal[...]` field as an inline enum rather than a named
# schema, so a generator has nowhere to hang a name — the values arrive typed,
# but only as part of whichever field carries them. Naming the field here gives
# the alias one source: change the backend's Literal and the alias changes with
# it, remove the field and this fails the generation.
#
# Every other site with the same value set picks the alias up automatically,
# which is why `on_error` is named once and lands on all eleven operation
# variants, and why `calls.list(type=...)` is typed by naming it on the response.
VOCABULARY: dict[tuple[str, str], str] = {
    ("AgentConfig", "channel"): "AgentChannel",
    ("CallBatchRecipientResponse", "status"): "CallBatchRecipientStatus",
    ("CallBatchResponse", "status"): "CallBatchStatus",
    ("CallSummaryResponse", "outcome"): "CallOutcome",
    ("CallSummaryResponse", "type"): "CallType",
    ("ConversationItemResponse", "delivery_status"): "DeliveryStatus",
    ("ConversationItemResponse", "direction"): "ConversationItemDirection",
    ("ConversationItemResponse", "role"): "ConversationItemRole",
    ("ConversationItemResponse", "type"): "ConversationItemType",
    ("ConversationItemResponse", "visibility"): "ConversationItemVisibility",
    ("EmailBatchResponse", "status"): "EmailBatchStatus",
    ("EmailRecipientResponse", "status"): "EmailRecipientStatus",
    ("HttpOperation", "on_error"): "OnError",
    ("LLMModelSpec", "reasoning_effort"): "ReasoningEffort",
    ("ObservabilityEndingResponse", "bucket"): "ObservabilityCloseReasonBucket",
    ("ObservabilityLatencyMetricResponse", "metric"): "ObservabilityLatencyMetric",
    ("ObservabilityRangeResponse", "granularity"): "ObservabilityGranularity",
    ("PhoneNumberResponse", "readiness"): "NumberReadiness",
    ("SetVariableConfig", "store"): "PublishStore",
    ("TaskRunError", "type"): "TaskErrorType",
    ("TelephonyAccountResponse", "provider"): "TelephonyProvider",
    ("TelephonyAccountResponse", "status"): "TelephonyAccountStatus",
}

# A second name for a vocabulary that already has one. Two names cannot both be
# derived from one set of values, so the second is written as what it is: the
# same thing, reachable by the name its own surface uses for it.
NAME_ALIASES: dict[str, str] = {
    # `observability.get(channel=...)` filters by the three channels an agent is
    # built for.
    "ObservabilityChannel": "AgentChannel",
}

# A `oneOf` is an anonymous union, so it needs a name from outside the document.
# Keyed by its sorted members, which is the only part of a union that cannot
# change without the union itself changing. A set that reaches here unnamed
# fails the generation rather than acquiring an invented name.
UNION_NAMES: dict[tuple[str, ...], str] = {
    # A tool's operation tree, and the same union nested under an `if`.
    (
        "AddMessageOperation",
        "CodeOperation",
        "EndCallOperation",
        "FrontendRpcOperation",
        "GenerateReplyOperation",
        "HandoffOperation",
        "HttpOperation",
        "IfOperation",
        "SayOperation",
        "SendDtmfOperation",
        "SetVariableOperation",
        "TransferOperation",
    ): "OperationRequest",
    # A batch's daily limit: a fixed number, or a ramp.
    ("FixedDailyCap", "RampDailyCap"): "DailyCap",
    # One page of `catalog.models.search`, per `kind`.
    ("LLMModelSearchResponse", "STTModelSearchResponse"): "ModelSearchResponse",
    # One row on a CoPilot rail.
    (
        "CopilotFunctionCallItem",
        "CopilotFunctionCallOutputItem",
        "CopilotTextItem",
    ): "CopilotItem",
    # The three event streams. Each frame repeats its name in its own `event`
    # field, so one `event["event"]` identifies the frame and narrows the union.
    (
        "AssistantCompletedEvent",
        "AssistantDeltaEvent",
        "AssistantStartedEvent",
        "ConversationSnapshotEvent",
        "ItemCreatedEvent",
        "ItemDeliveryUpdatedEvent",
        "TurnFailedEvent",
        "TurnPayload",
    ): "ConversationStreamEvent",
    (
        "CopilotMessageEvent",
        "CopilotSnapshotEvent",
        "TurnPayload",
    ): "CopilotStreamEvent",
}

# Unions the document has no construct for at all: a family of schemas that
# share a shape by inheritance, which Pydantic inlines into each concrete member
# rather than pointing at a base. Naming the family is what lets a caller write
# one function over it.
EXTRA_UNIONS: dict[str, list[str]] = {
    "CatalogEntry": [
        "LLMCatalogEntryResponse",
        "STTCatalogEntryResponse",
        "TTSCatalogEntryResponse",
        "RealtimeCatalogEntryResponse",
        "AvatarCatalogEntryResponse",
        "NoiseCancellationCatalogEntryResponse",
    ],
    "CatalogPricing": [
        "LLMPricing",
        "STTPricing",
        "TTSPricing",
        "RealtimePricing",
        "AvatarPricing",
    ],
    "PriceLine": [
        "LLMPriceLine",
        "STTPriceLine",
        "TTSPriceLine",
        "RealtimePriceLine",
        "AvatarPriceLine",
    ],
}

TYPES_HEADER = '''"""Every request and response shape the API has, as TypedDicts.

A response is the decoded JSON, so these describe it without touching it:
nothing here validates, coerces or renames a field, and a `str` typed from a
`date-time` is the ISO-8601 string the API actually sent.

A few schemas accept keys beyond the ones declared — a catalog entry carries
per-provider extras. A TypedDict has no way to say "and more", but the value is
a plain dict at runtime, so those are a `.get(...)` away.
"""

from __future__ import annotations

from typing import Any, Generic, Literal, TypeVar, Union

from typing_extensions import NotRequired, TypedDict

# Free-form JSON, for the fields the API accepts anything in: userdata, tool
# arguments, a tool's JSON Schema. Useful when a caller BUILDS one of those —
# it refuses a value that would not survive `json.dumps`. What comes back is
# typed `dict[str, Any]`, which is what the document says such a field is.
JsonValue = Union[str, int, float, bool, None, list["JsonValue"], dict[str, "JsonValue"]]

T = TypeVar("T")


class Page(TypedDict, Generic[T]):
    """One page of a list endpoint.

    Ask for the next with `offset=offset + limit`, or walk them all with
    `talqing.paginate`.
    """

    items: list[T]
    has_more: bool
    limit: int
    offset: int
'''


def snake(name: str) -> str:
    """`phoneNumbers` -> `phone_numbers`."""
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name).lower()


def attribute(name: str) -> str:
    """The Python name for one part of an operation id.

    A trailing underscore is PEP 8's answer to a name that collides with a
    keyword, and `telephony.phoneNumbers.import` is the one that does.
    """
    value = snake(name)
    return f"{value}_" if keyword.iskeyword(value) else value


def class_name(parts: list[str], *, is_async: bool) -> str:
    """`['calls', 'batches']` -> `_CallsBatches`.

    Named by the full path rather than the leaf, because leaves legitimately
    repeat — `calls.batches` and `email.batches`, `agents.versions` and
    `tools.versions` — and a de-duplicating suffix would be a worse name than
    the one the path already gives.
    """
    body = "".join(part[:1].upper() + part[1:] for part in parts)
    return f"_{'Async' if is_async else ''}{body}"


def root_name(is_async: bool) -> str:
    return "AsyncTalqingApi" if is_async else "TalqingApi"


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def docstring(text: str, indent: str) -> str:
    """A triple-quoted docstring for arbitrary prose out of the document."""
    body = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"').strip()
    lines = body.split("\n")
    if len(lines) == 1:
        return f'{indent}"""{lines[0]}"""'
    rest = "\n".join(f"{indent}{line}".rstrip() for line in lines[1:])
    return f'{indent}"""{lines[0]}\n{rest}\n{indent}"""'


def comment(text: str, indent: str) -> list[str]:
    out: list[str] = []
    for paragraph in text.strip().split("\n"):
        wrapped = textwrap.wrap(paragraph.strip(), width=88 - len(indent) - 2) or [""]
        out.extend(f"{indent}# {line}".rstrip() for line in wrapped)
    return out


def enum_of(schema: Any) -> tuple[Any, ...] | None:
    if not isinstance(schema, dict):
        return None
    if "enum" in schema:
        return tuple(schema["enum"])
    for key in ("anyOf", "oneOf"):
        for option in schema.get(key) or []:
            found = enum_of(option)
            if found:
                return found
    return enum_of(schema.get("items"))


class Types:
    """Schema -> Python type expression, and the emitter for `gen/types.py`."""

    def __init__(self, schemas: dict[str, Any]) -> None:
        self.schemas = schemas
        self.enum_names: dict[tuple[Any, ...], str] = {}
        self.pages: dict[str, str] = {}  # PageAgentResponse -> AgentResponse
        self._name_vocabularies()
        self._find_pages()

    def _name_vocabularies(self) -> None:
        for (schema, prop), alias in VOCABULARY.items():
            try:
                node = self.schemas[schema]["properties"][prop]
            except KeyError:
                raise SystemExit(
                    f"VOCABULARY names {schema}.{prop}, which the document does "
                    "not have. Point it at the field carrying those values now, "
                    "or drop the entry."
                ) from None
            values = enum_of(node)
            if values is None:
                raise SystemExit(
                    f"VOCABULARY names {schema}.{prop}, which is not an enum — "
                    "only a field with a fixed set of values can name a vocabulary."
                )
            clash = self.enum_names.get(values)
            if clash and clash != alias:
                raise SystemExit(
                    f"{alias} and {clash} name the same values {list(values)}. One "
                    "value set carries one name — put the second in NAME_ALIASES."
                )
            self.enum_names[values] = alias

    def _find_pages(self) -> None:
        """`PageAgentResponse` -> `Page[AgentResponse]`, detected by shape.

        Keyed on the structure rather than the name, so a schema that merely
        starts with `Page` cannot be mistaken for one, and a page that gains a
        field degrades into an ordinary TypedDict instead of a wrong alias.
        """
        shape = ["has_more", "items", "limit", "offset"]
        for name, schema in self.schemas.items():
            props = schema.get("properties") or {}
            if sorted(props) != shape or sorted(schema.get("required") or []) != shape:
                continue
            items = props["items"]
            if items.get("type") != "array" or "$ref" not in (items.get("items") or {}):
                continue
            self.pages[name] = ref_name(items["items"]["$ref"])

    def expr(self, schema: dict[str, Any]) -> str:
        if "$ref" in schema:
            return ref_name(schema["$ref"])
        if "const" in schema:
            return f"Literal[{schema['const']!r}]"
        if "enum" in schema:
            values = tuple(schema["enum"])
            named = self.enum_names.get(values)
            return named or "Literal[" + ", ".join(repr(v) for v in values) + "]"
        if "oneOf" in schema:
            members = tuple(sorted(ref_name(o["$ref"]) for o in schema["oneOf"]))
            try:
                return UNION_NAMES[members]
            except KeyError:
                raise SystemExit(
                    "the document has a union with no name:\n  "
                    + ", ".join(members)
                    + "\nAdd it to UNION_NAMES — a union a caller switches on needs "
                    "a name they can write down."
                ) from None
        if "anyOf" in schema:
            parts: list[str] = []
            for option in schema["anyOf"]:
                part = self.expr(option)
                if part not in parts:
                    parts.append(part)
            return " | ".join(parts)

        kind = schema.get("type")
        if kind == "null":
            return "None"
        if kind == "array":
            return f"list[{self.expr(schema['items'])}]"
        if kind == "object":
            extra = schema.get("additionalProperties")
            if isinstance(extra, dict):
                return f"dict[str, {self.expr(extra)}]"
            return "dict[str, Any]"
        if kind == "string":
            return "bytes" if schema.get("format") == "binary" else "str"
        if kind == "integer":
            return "int"
        if kind == "number":
            return "float"
        if kind == "boolean":
            return "bool"
        if kind is None:
            # `IfConfig.left` and `.right` compare whatever the tool produced.
            return "Any"
        raise SystemExit(f"no Python type for schema {json.dumps(schema)[:200]}")

    def render(self) -> str:
        blocks: list[str] = []
        exported: list[str] = ["JsonValue", "Page"]

        for name, schema in sorted(self.schemas.items()):
            if name in self.pages:
                continue
            blocks.append(self._declaration(name, schema))
            exported.append(name)

        aliases: list[str] = []

        def alias(name: str, body: str) -> None:
            aliases.append(f"{name} = {body}")
            exported.append(name)

        for members, name in sorted(UNION_NAMES.items(), key=lambda kv: kv[1]):
            alias(name, " | ".join(members))
        for name, members in sorted(EXTRA_UNIONS.items()):
            missing = [m for m in members if m not in self.schemas]
            if missing:
                raise SystemExit(
                    f"EXTRA_UNIONS['{name}'] names missing schemas: {missing}"
                )
            alias(name, " | ".join(members))
        for values, name in sorted(self.enum_names.items(), key=lambda kv: kv[1]):
            alias(name, "Literal[" + ", ".join(repr(v) for v in values) + "]")
        for name, target in sorted(NAME_ALIASES.items()):
            alias(name, target)
        for name, item in sorted(self.pages.items()):
            alias(name, f"Page[{item}]")

        listed = ",\n    ".join(f'"{name}"' for name in sorted(set(exported)))
        return (
            BANNER
            + TYPES_HEADER
            + "\n\n"
            + "\n\n\n".join(blocks)
            + "\n\n\n"
            + "\n".join(aliases)
            + f"\n\n__all__ = [\n    {listed},\n]\n"
        )

    def _declaration(self, name: str, schema: dict[str, Any]) -> str:
        props: dict[str, Any] = schema.get("properties") or {}
        if not props:
            # An enum, a free-form object, or anything else the backend models
            # as a bare value rather than a record.
            head = (
                comment(schema["description"], "") if schema.get("description") else []
            )
            return "\n".join([*head, f"{name} = {self.expr(schema)}"])

        required = set(schema.get("required") or [])
        lines: list[str] = []

        # A wire key that is not a Python identifier can only be written with the
        # functional form, where every annotation is a string resolved later —
        # which is also what keeps a recursive union working there.
        if any(not key.isidentifier() or keyword.iskeyword(key) for key in props):
            if schema.get("description"):
                lines.extend(comment(schema["description"], ""))
            lines.append(f"{name} = TypedDict(")
            lines.append(f'    "{name}",')
            lines.append("    {")
            for key, prop in props.items():
                if prop.get("description"):
                    lines.extend(comment(prop["description"], "        "))
                lines.append(
                    f'        "{key}": "{self._annotation(prop, key in required)}",'
                )
            lines.append("    },")
            lines.append(")")
            return "\n".join(lines)

        lines.append(f"class {name}(TypedDict):")
        if schema.get("description"):
            lines.append(docstring(schema["description"], "    "))
            lines.append("")
        for key, prop in props.items():
            if prop.get("description"):
                lines.extend(comment(prop["description"], "    "))
            lines.append(f"    {key}: {self._annotation(prop, key in required)}")
        return "\n".join(lines)

    def _annotation(self, prop: dict[str, Any], required: bool) -> str:
        expression = self.expr(prop)
        return expression if required else f"NotRequired[{expression}]"


class Operation:
    """One endpoint, resolved into everything its method needs."""

    def __init__(
        self,
        spec: dict[str, Any],
        types: Types,
        path: str,
        verb: str,
        node: dict[str, Any],
    ) -> None:
        self.id: str = node["operationId"]
        self.verb = verb.upper()
        self.path = path
        self.types = types
        self.summary: str = node.get("summary", "")
        self.description: str = node.get("description", "")

        parameters = node.get("parameters", [])
        self.path_params = [p for p in parameters if p["in"] == "path"]
        self.query_params = [p for p in parameters if p["in"] == "query"]

        self.body: dict[str, Any] = {}
        request = node.get("requestBody")
        if request:
            ref = request["content"]["application/json"]["schema"]["$ref"]
            self.body = spec["components"]["schemas"][ref_name(ref)]

        self.kind, self.result = self._result(node)
        if self.kind == "stream" and self.verb != "GET":
            raise SystemExit(f"{self.id} streams over {self.verb}; only GET is handled")

    @property
    def parts(self) -> list[str]:
        return self.id.split(".")

    @property
    def body_props(self) -> dict[str, Any]:
        return self.body.get("properties") or {}

    def _result(self, node: dict[str, Any]) -> tuple[str, str]:
        code = sorted(c for c in node["responses"] if c.startswith("2"))[0]
        content = node["responses"][code].get("content")
        if not content:
            return "none", "None"
        media, body = next(iter(content.items()))
        if media == "text/event-stream":
            return "stream", self.types.expr(body["schema"])
        if media != "application/json":
            return "bytes", "bytes"
        return "json", self.types.expr(body["schema"])

    def arguments(self) -> tuple[list[tuple[str, str]], list[tuple[str, str, bool]]]:
        """(path arguments, keyword arguments), each in the order they are declared."""
        positional = [
            (p["name"], self.types.expr(p["schema"])) for p in self.path_params
        ]

        needed = set(self.body.get("required") or [])
        required: list[tuple[str, str, bool]] = []
        optional: list[tuple[str, str, bool]] = []
        for key, schema in self.body_props.items():
            entry = (key, self.types.expr(schema), key in needed)
            (required if key in needed else optional).append(entry)
        for param in self.query_params:
            entry = (
                param["name"],
                self.types.expr(param["schema"]),
                bool(param.get("required")),
            )
            (required if param.get("required") else optional).append(entry)
        return positional, required + optional

    def documentation(self) -> str:
        text = self.description or self.summary
        described = [
            (key, schema["description"])
            for key, schema in self.body_props.items()
            if schema.get("description")
        ]
        described += [
            (p["name"], p.get("description") or p["schema"]["description"])
            for p in self.query_params
            if p.get("description") or p["schema"].get("description")
        ]
        if described:
            rows = [
                "    "
                + textwrap.fill(
                    f"{key}: {' '.join(note.split())}",
                    width=84,
                    subsequent_indent="        ",
                )
                for key, note in described
            ]
            text = f"{text}\n\nArgs:\n" + "\n".join(rows)
        defaults = [
            f"{p['name']}={p['schema']['default']!r}"
            for p in self.query_params
            if "default" in p["schema"]
        ]
        if defaults:
            text += f"\n\nOmitted parameters take the server's default: {', '.join(defaults)}."
        return text


# What `api.py` puts in module scope. A method of the same name shadows it for
# every annotation in that class body, and `from __future__ import annotations`
# defers the failure from import time to whenever someone runs a type checker.
# `list` and `dict` are missing on purpose — `agents.list` is a name we publish,
# and `as_input` is what keeps it out of the way.
RESERVED_NAMES = {
    "Any",
    "AsyncStream",
    "AsyncTransport",
    "Literal",
    "Mapping",
    "OMIT",
    "Sequence",
    "Stream",
    "TYPE_CHECKING",
    "Transport",
    "bool",
    "bytes",
    "float",
    "int",
    "str",
}


class Api:
    """The resource tree, emitted twice: once synchronous, once not."""

    def __init__(self, operations: list[Operation]) -> None:
        self.operations = operations
        self.tree: dict[str, Any] = {}
        for operation in operations:
            node = self.tree
            for part in operation.parts[:-1]:
                node = node.setdefault(part, {})
            node.setdefault("", []).append(operation)
        self._assert_no_shadowing(self.tree, "")

    def _assert_no_shadowing(self, node: dict[str, Any], prefix: str) -> None:
        methods = {attribute(op.parts[-1]) for op in node.get("", [])}
        children = {attribute(key) for key in node if key != ""}
        clash = sorted(methods & children)
        if clash:
            raise SystemExit(
                f"under '{prefix or 'the client'}', {clash} is both a method and a "
                "sub-resource. One of the two operation ids in "
                "backend/api/sdk_surface.py has to move."
            )
        reserved = sorted(methods & RESERVED_NAMES)
        if reserved:
            raise SystemExit(
                f"under '{prefix or 'the client'}', {reserved} would shadow a name "
                "the generated module needs for its own annotations. Rename the "
                "operation in backend/api/sdk_surface.py."
            )
        for key, child in node.items():
            if key != "":
                self._assert_no_shadowing(child, f"{prefix}.{key}" if prefix else key)

    def render(self, *, is_async: bool) -> str:
        used: set[str] = set()
        blocks: list[str] = []
        self._emit(self.tree, [], blocks, used, is_async)
        body = "\n\n\n".join(blocks)

        stream = "AsyncStream" if is_async else "Stream"
        client = "AsyncTalqing" if is_async else "Talqing"
        typing_names = ["TYPE_CHECKING"] + [
            name
            for name in ("Any", "Literal", "Mapping", "Sequence")
            if re.search(rf"\b{name}\b", body)
        ]
        return (
            BANNER
            + f'"""The {"asynchronous" if is_async else "synchronous"} API surface.\n'
            "\n"
            "One method per operation id in `backend/api/sdk_surface.py`, so\n"
            f"`agents.versions.rollback` is `{'await ' if is_async else ''}"
            "client.agents.versions.rollback(...)`.\n"
            f"Reach them through `talqing.{client}`, which is what holds the\n"
            "credentials — these classes are not constructed directly.\n"
            '"""\n\n'
            "from __future__ import annotations\n\n"
            f"from typing import {', '.join(typing_names)}\n\n"
            f"from .._transport import OMIT, {stream}, encode_path as _p\n"
            + "from .types import (\n    "
            + ",\n    ".join(sorted(used))
            + ",\n)\n\n"
            "if TYPE_CHECKING:\n"
            f"    from .._transport import {'Async' if is_async else ''}Transport\n\n\n"
            + body
            + "\n"
        )

    def _emit(
        self,
        node: dict[str, Any],
        parts: list[str],
        blocks: list[str],
        used: set[str],
        is_async: bool,
    ) -> None:
        children = sorted(key for key in node if key != "")
        for key in children:
            self._emit(node[key], parts + [key], blocks, used, is_async)

        name = class_name(parts, is_async=is_async) if parts else root_name(is_async)
        transport = f"{'Async' if is_async else ''}Transport"
        lines = [f"class {name}:"]

        if not parts:
            lines.append(
                docstring(
                    "Every operation the API has, reached by resource.\n"
                    "\n"
                    f"Built for you by `{'AsyncTalqing' if is_async else 'Talqing'}`.",
                    "    ",
                )
            )
            lines.append("")

        for key in children:
            child = class_name(parts + [key], is_async=is_async)
            lines.append(f"    {attribute(key)}: {child}")
        if children:
            lines.append("")

        lines.append(f'    def __init__(self, transport: "{transport}") -> None:')
        lines.append("        self._t = transport")
        for key in children:
            child = class_name(parts + [key], is_async=is_async)
            lines.append(f"        self.{attribute(key)} = {child}(transport)")

        for operation in sorted(node.get("", []), key=lambda o: o.id):
            lines.append("")
            lines.extend(self._method(operation, used, is_async))

        blocks.append("\n".join(lines))

    def _method(
        self, operation: Operation, used: set[str], is_async: bool
    ) -> list[str]:
        positional, keywords = operation.arguments()
        for _, annotation in positional:
            used.update(referenced(annotation))
        for _, annotation, _required in keywords:
            used.update(referenced(annotation))
        used.update(referenced(operation.result))

        result = operation.result
        if operation.kind == "stream":
            result = f"{'AsyncStream' if is_async else 'Stream'}[{result}]"

        # A stream method is not a coroutine even on the async client: it hands
        # back an `AsyncStream`, so `async for event in client.…events(id)`
        # reads the way the synchronous `for` does instead of needing an await
        # in front of it.
        coroutine = is_async and operation.kind != "stream"
        lines = [
            f"    {'async ' if coroutine else ''}def {attribute(operation.parts[-1])}("
        ]
        lines.append("        self,")
        for arg, annotation in positional:
            lines.append(f"        {arg}: {as_input(annotation)},")
        if keywords:
            lines.append("        *,")
            for arg, annotation, required in keywords:
                default = "" if required else " = OMIT"
                lines.append(f"        {arg}: {as_input(annotation)}{default},")
        lines.append(f"    ) -> {result}:")
        lines.append(docstring(operation.documentation(), "        "))
        lines.append(self._call(operation, positional, is_async))
        return lines

    def _call(
        self, operation: Operation, positional: list[tuple[str, str]], is_async: bool
    ) -> str:
        url = operation.path
        for arg, _ in positional:
            url = url.replace("{" + arg + "}", "{_p(" + arg + ")}")
        target = f'f"{url}"' if positional else f'"{url}"'

        arguments: list[str] = []
        if operation.kind != "stream":
            arguments.append(f'"{operation.verb}"')
        arguments.append(target)
        if operation.query_params:
            pairs = ", ".join(
                f'"{p["name"]}": {p["name"]}' for p in operation.query_params
            )
            arguments.append(f"query={{{pairs}}}")
        if operation.body_props:
            pairs = ", ".join(f'"{key}": {key}' for key in operation.body_props)
            arguments.append(f"body={{{pairs}}}")
        if operation.kind in ("none", "bytes"):
            arguments.append(f'expect="{operation.kind}"')

        call = "self._t.stream" if operation.kind == "stream" else "self._t.request"
        lead = "" if operation.kind == "none" else "return "
        if is_async and operation.kind != "stream":
            lead += "await "
        return f"        {lead}{call}({', '.join(arguments)})"


def as_input(expression: str) -> str:
    """The same type, written for a parameter rather than a field.

    `Sequence`/`Mapping` because an argument is naturally covariant — a tuple of
    operations is as good as a list of them — and because a resource whose
    operation id is `list` defines a method of that name, which would shadow the
    builtin for every annotation in the same class body. `assert_no_shadowing`
    keeps the rest of the module's names out of that trap; this one cannot be
    fixed that way, because `list` is a name we publish on purpose.
    """
    expression = re.sub(r"\blist\[", "Sequence[", expression)
    return re.sub(r"\bdict\[", "Mapping[", expression)


BUILTIN_NAMES = {
    "Any",
    "None",
    "True",
    "False",
    "str",
    "int",
    "float",
    "bool",
    "bytes",
    "list",
    "dict",
    "Literal",
    "Sequence",
    "Mapping",
    "Stream",
    "AsyncStream",
    "OMIT",
}


def referenced(annotation: str) -> set[str]:
    """The type names an annotation mentions, for `api.py`'s import list."""
    without_literals = re.sub(r"'[^']*'|\"[^\"]*\"", "", annotation)
    names = set(re.findall(r"[A-Za-z_][A-Za-z0-9_]*", without_literals))
    return {name for name in names if name not in BUILTIN_NAMES and not name.islower()}


def assert_expandable(operations: list[Operation]) -> None:
    """Expanding a body into keyword arguments is only safe while nothing clashes."""
    for operation in operations:
        taken = {p["name"] for p in operation.path_params + operation.query_params}
        clash = sorted(taken & set(operation.body_props))
        if clash:
            raise SystemExit(
                f"{operation.id} has {clash} as both a body field and a path or "
                "query parameter, so they cannot both be keyword arguments. Rename "
                "one in the backend, or move this generator to a single `body=`."
            )
        unnameable = [
            p["name"]
            for p in operation.path_params + operation.query_params
            if not p["name"].isidentifier() or keyword.iskeyword(p["name"])
        ]
        if unnameable:
            raise SystemExit(
                f"{operation.id} has parameters Python cannot name: {unnameable}"
            )
        for key in operation.body_props:
            if not key.isidentifier() or keyword.iskeyword(key):
                raise SystemExit(
                    f"{operation.id} has a body field Python cannot name as an "
                    f"argument: {key!r}."
                )


def build() -> dict[Path, str]:
    spec = json.loads(SPEC.read_text())
    types = Types(spec["components"]["schemas"])

    operations = [
        Operation(spec, types, path, verb, node)
        for path, item in spec["paths"].items()
        for verb, node in item.items()
        if verb in HTTP_METHODS
    ]
    assert_expandable(operations)
    api = Api(operations)

    return {
        OUT / "types.py": types.render(),
        OUT / "api.py": api.render(is_async=False),
        OUT / "async_api.py": api.render(is_async=True),
        OUT / "__init__.py": (
            BANNER
            + '"""The generated half of the SDK. Import from `talqing`, not from here."""\n\n'
            "from .api import TalqingApi\n"
            "from .async_api import AsyncTalqingApi\n"
            "from .types import *  # noqa: F403\n"
            "from .types import __all__ as _types\n\n"
            '__all__ = ["TalqingApi", "AsyncTalqingApi", *_types]\n'
        ),
    }


def formatted(files: dict[Path, str]) -> dict[Path, str]:
    """Run the tree through ruff, because pre-commit runs ruff over it anyway."""
    ruff = shutil.which("ruff") or str(REPO / ".venv" / "bin" / "ruff")
    if not Path(ruff).exists():
        raise SystemExit(
            "ruff is not installed, and this has to emit an already-formatted "
            "tree — pre-commit runs ruff-format over it. Run `uv sync` in the "
            "repository root."
        )
    out: dict[Path, str] = {}
    for path, source in files.items():
        done = subprocess.run(
            [ruff, "format", "--quiet", "--stdin-filename", str(path), "-"],
            input=source,
            capture_output=True,
            text=True,
        )
        if done.returncode != 0:
            raise SystemExit(f"ruff format failed on {path.name}:\n{done.stderr}")
        out[path] = done.stdout
    return out


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate clients/python/src/talqing/gen."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in tree is not what the document generates",
    )
    arguments = parser.parse_args()
    files = formatted(build())

    if arguments.check:
        stale = [
            path.relative_to(REPO)
            for path, source in files.items()
            if not path.exists() or path.read_text() != source
        ]
        if stale:
            print(
                "the generated Python SDK is behind openapi/openapi.json:\n"
                + "\n".join(f"  {path}" for path in stale)
                + "\nRun `python clients/python/generate.py`.",
                file=sys.stderr,
            )
            raise SystemExit(1)
        print(f"{len(files)} generated files are up to date")
        return

    OUT.mkdir(parents=True, exist_ok=True)
    for path, source in files.items():
        path.write_text(source)
        print(f"wrote {path.relative_to(REPO)} ({len(source.splitlines()):,} lines)")


if __name__ == "__main__":
    main()
