"""Export the API contract to checked-in files.

There are two apps, so there are two documents — and only one of them is
published:

- ``openapi/openapi.json`` — the REGIONAL API. This is the contract: both SDKs in
  ``clients/`` and ``mcp/tools.json`` are generated from it, so an integrator
  holds one base URL and one token and no published method can express a call to
  the other plane. ``documentation/openapi.json`` is the same document plus the
  region base URLs and the auth scheme, which is what the rendered API reference
  reads and what a generator input must not carry.
- ``openapi/control.json`` — the CONTROL API, published nowhere. Its one consumer
  is the dashboard's client in ``frontend/lib/control/``, generated by the same
  generator. Hand-maintaining those 17 endpoints and their types in the frontend
  is the drift ``services/user/tenants.py`` exists to warn about.

Plus the two agent-facing artifacts, both regional:

- ``mcp/tools.json`` — the functions from ``api.dataplane.functions``, the tool
  list the MCP server serves.
- ``mcp/SKILL.md`` — ``backend/services/copilot/skill.md``, the platform
  knowledge CoPilot is prompted with, packaged as a skill.

The last two are what keep an external Claude Code or Codex on the same footing
as our own CoPilot: same functions, same knowledge, one generator.

Usage:
    PYTHONPATH=backend python openapi/export.py

Uses two minimal in-memory Settings — one per node — so export needs no filled
config file. Each app asserts its own role at import, which is exactly why the
settings are swapped between the two imports below rather than one object being
made to satisfy both.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

os.environ.setdefault("ENV", "local.in")

from settings import Settings, configure_settings  # noqa: E402

# Ed25519 keys are parsed at config load, so the export needs a real pair. This
# one is generated fresh per run, signs nothing, and never leaves this process.
from cryptography.hazmat.primitives import serialization  # noqa: E402
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey  # noqa: E402

_key = Ed25519PrivateKey.generate()
_SIGNING_PEM = _key.private_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PrivateFormat.PKCS8,
    encryption_algorithm=serialization.NoEncryption(),
).decode()
_VERIFY_PEM = (
    _key.public_key()
    .public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    .decode()
)
# 32 hex characters, which is the floor the config enforces. Authenticates
# nothing here: no request is made during an export.
_EXPORT_TOKEN = "export" + "0" * 26

# `code_exec_url` is region-only — the settings model refuses it on control — so
# it is added to the regional object below rather than shared here.
_APP_URLS = {
    "api_public_url": "http://localhost:8000",
    "dashboard_public_url": "http://localhost:3000",
}

REGION_SETTINGS = Settings.model_validate(
    {
        "env": "local",
        "role": "region",
        "region": "in",
        "security": {
            # Must be a real Fernet key — SecurityConfig validates the format so a
            # broken key fails at boot rather than at first decrypt. This one is
            # base64("openapi-export-only-not-a-secret"); it encrypts nothing, and
            # decoding it says so.
            "secrets_fernet_key": "b3BlbmFwaS1leHBvcnQtb25seS1ub3QtYS1zZWNyZXQ=",  # gitleaks:allow
            "chat_token_secret": "openapi-export-only-chat-token-secret",
            "session_cookie_name": "talqing_session",
            "session_verify_key": _VERIFY_PEM,
            "oauth_state_key": "openapi-export-only-state-secret",
        },
        "control": {
            "api_url": "http://localhost:8001",
            "internal_token": _EXPORT_TOKEN,
        },
        "app": {**_APP_URLS, "code_exec_url": "http://localhost:8080"},
        # Nothing here connects — the export only needs a valid object.
        # pool_max_size has no default because it is a per-process ceiling every
        # environment must state for itself.
        "postgres": {
            "data": {
                "default_dsn": "postgresql://talqing:talqing@localhost:5432/talqing_data",
                "pool_max_size": 10,
            },
        },
        "redis": {"url": "redis://localhost:6379/0"},
        "kafka": {"bootstrap_servers": "localhost:29092"},
        "livekit": {
            "url": "ws://localhost:7880",
            "public_urls": [
                "ws://localhost:7880",
                "ws://localhost:7880",
                "ws://localhost:7880",
            ],
            "api_key": "devkey",
            "api_secret": "devsecret",
            "agent_name": "talqing-agent",
            "sip": {
                "whatsapp": {
                    "username": "export",
                    "password": "export-only-not-a-secret",
                }
            },
        },
        # Nothing is uploaded or signed during export; the object only has to
        # validate.
        "storage": {
            "endpoint_url": "https://sfo3.digitaloceanspaces.com",
            "region": "us-east-1",
            "recordings": {
                "name": "talqing-recordings",
                "access_key": "export-only",
                "secret_key": "export-only",
            },
            "attachments": {
                "name": "talqing-attachments",
                "access_key": "export-only",
                "secret_key": "export-only",
            },
        },
        "providers": {
            "xai": {
                "api_key": "xai-export-only",
                "base_url": "https://api.x.ai/v1",
            },
            "sarvam": {"api_key": "sarvam-export-only"},
            "gemini": {"api_key": "gemini-export-only"},
            # Required rather than defaulted (`ExaProviderConfig`), so the export
            # cannot validate without it — even though it never reaches the web.
            "exa": {"api_key": "exa-export-only"},
        },
    }
)

CONTROL_SETTINGS = Settings.model_validate(
    {
        "env": "local",
        "role": "control",
        "security": {
            "session_cookie_name": "talqing_session",
            "session_signing_key": _SIGNING_PEM,
            "session_verify_key": _VERIFY_PEM,
            "oauth_state_key": "openapi-export-only-state-secret",
        },
        "app": _APP_URLS,
        "regions": [
            {
                "slug": "in",
                "name": "India (Bangalore)",
                "api_url": "http://localhost:8000",
                "internal_token": _EXPORT_TOKEN,
                "countries": ["IN"],
                "default": True,
            }
        ],
        "postgres": {
            "control": {
                "dsn": "postgresql://talqing:talqing@localhost:5432/talqing_control",
                "pool_max_size": 10,
            },
        },
    }
)

configure_settings(REGION_SETTINGS)

from api.dataplane.main import app as dataplane_app  # noqa: E402
from api.dataplane.functions import registry  # noqa: E402
from services.copilot.prompt import SKILL_PATH, skill  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
OPENAPI_OUT = Path(__file__).with_name("openapi.json")
CONTROL_OUT = Path(__file__).with_name("control.json")
TOOLS_OUT = REPO / "mcp" / "tools.json"
SKILL_OUT = REPO / "mcp" / "SKILL.md"
# The same regional document, plus the two things a rendered API reference needs
# and a generator input must not carry: the region base URLs to offer in its
# "try it" panel, and the scheme every operation authenticates with. Written
# here rather than kept by hand, because the copy that was kept by hand fell
# four endpoints behind the spec it was supposed to be.
DOCS_OUT = REPO / "documentation" / "openapi.json"
DOCS_SERVERS = [
    {"url": "https://api.in.talqing.com", "description": "India (in)"},
    {"url": "https://api.us.talqing.com", "description": "United States (us)"},
]

# An MCP client loads the whole tool list before the user has typed anything, so
# this is a floor on what our server costs a session. It reached ~600k
# characters once — more than a 200k-context client can hold, empty — for the
# honest reason that nothing counted it.
#
# Today it is well under that, because every function defers its argument schema
# to `describe_function` and only its name and description are carried. The cap
# stays where it is so that re-inlining one `DEFERRED_SCHEMAS` document (39k on
# its own) fails the export that does it rather than three releases later.
MAX_TOOL_SURFACE_CHARS = 150_000

SKILL_FRONTMATTER = """---
name: talqing
description: >-
  Build, publish and operate Talqing AI voice, video and text agents — agent
  config and model stack, custom tools and their operation trees, MCP and
  messaging integrations, phone numbers, secrets and webhooks, plus placing
  calls and reading back transcripts, cost and latency. Use whenever working
  against a Talqing workspace through the talqing MCP server.
---
"""


def _generated_note(source: str) -> str:
    return (
        f"<!-- Generated by openapi/export.py from {source}. Edit that file, "
        "then re-run the export. -->"
    )


def _tools() -> dict:
    """The MCP tool list, straight from the function registry.

    Path parameters are the `{name}` placeholders in `path`; every other
    top-level argument is a query parameter, and `body` is the JSON body. That
    is all a client needs to turn a tool call into the HTTP request.
    """
    return {
        "api_version": dataplane_app.version,
        "api_prefix": "/v1",
        "tools": [
            {
                "name": fn.name,
                "method": fn.method,
                "path": fn.path,
                "description": fn.summary,
                "role": fn.role,
                "read_only": fn.read_only,
                "parameters": fn.parameters,
            }
            for fn in registry().values()
        ],
    }


def _size(value) -> int:
    return len(json.dumps(value, separators=(",", ":")))


def _check_tool_surface(tools: dict) -> int:
    """Refuse to export a tool list too big for the context of the client loading it.

    Weighs what the server actually hands a client on connect: each tool's
    argument schema AND its description. The descriptions are nearly half of it,
    and they are the half that creeps — every new endpoint adds one, and a
    docstring has no natural ceiling the way a schema does.
    """
    total = sum(_size(tool) for tool in tools["tools"])
    if total <= MAX_TOOL_SURFACE_CHARS:
        return total
    biggest = sorted(tools["tools"], key=_size, reverse=True)[:5]
    raise SystemExit(
        f"the tool surface is {total:,} characters, over the "
        f"{MAX_TOOL_SURFACE_CHARS:,} ceiling — and an MCP client loads all of it "
        "before the user types anything.\nThe largest are:\n"
        + "\n".join(
            f"  {t['name']:<32}{_size(t):>7,}"
            f"  ({_size(t['parameters']):,} schema, {_size(t['description']):,} description)"
            for t in biggest
        )
        + "\nDefer the type a schema carries (api.dataplane.functions.DEFERRED_SCHEMAS), or "
        "shorten the route docstring, rather than raising the ceiling."
    )


def _control_document() -> dict:
    """Build the control app's document, with control's own settings installed.

    Imported here rather than at module scope: each ``main.py`` asserts at import
    that the loaded config is for its own role, so the two apps cannot be built
    under one settings object — which is the assertion doing its job.
    """
    configure_settings(CONTROL_SETTINGS)
    from api.control.main import app as control_app

    document = control_app.openapi()
    configure_settings(REGION_SETTINGS)
    return document


def _no_leak(document: dict, forbidden: tuple[str, ...], name: str) -> None:
    """Two documents, and neither may carry the other's paths.

    Cheap, and it is the check that would have caught a route left on the wrong
    app: a control route in the published document reaches every SDK and the MCP
    tool list, which is exactly what the split exists to prevent.
    """
    leaked = sorted(
        path for path in document.get("paths", {}) if path.startswith(forbidden)
    )
    if leaked:
        raise SystemExit(
            f"{name} carries paths belonging to the other plane: {', '.join(leaked)}"
        )


def main() -> None:
    tools = _tools()
    surface = _check_tool_surface(tools)

    published = dataplane_app.openapi()
    _no_leak(
        published,
        ("/v1/orgs", "/v1/org", "/v1/tokens", "/v1/auth", "/v1/regions"),
        "openapi.json",
    )
    control = _control_document()
    _no_leak(
        control,
        ("/v1/agents", "/v1/calls", "/v1/tools", "/v1/billing/credits"),
        "control.json",
    )

    OPENAPI_OUT.write_text(json.dumps(published, indent=2, sort_keys=True) + "\n")
    CONTROL_OUT.write_text(json.dumps(control, indent=2, sort_keys=True) + "\n")
    DOCS_OUT.write_text(
        json.dumps(
            {**published, "servers": DOCS_SERVERS, "security": [{"BearerAuth": []}]},
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )
    # sort_keys, like the OpenAPI documents above: Pydantic emits each function's
    # `$defs` in whatever order it walked the models, which varies run to run and
    # reordered ~400 lines of a checked-in artifact every export, burying the one
    # line that actually changed.
    TOOLS_OUT.write_text(json.dumps(tools, indent=2, sort_keys=True) + "\n")
    SKILL_OUT.write_text(
        f"{SKILL_FRONTMATTER}\n{_generated_note(SKILL_PATH.relative_to(REPO))}\n\n{skill()}\n"
    )
    for path in (OPENAPI_OUT, CONTROL_OUT, DOCS_OUT, TOOLS_OUT, SKILL_OUT):
        print(f"wrote {path.relative_to(REPO)}")
    # Printed every export, because the only reason this grew to 600k characters
    # unnoticed is that no one ever saw the number.
    print(
        f"\non connect an MCP client loads {len(tools['tools'])} tools "
        f"({surface:,} of {MAX_TOOL_SURFACE_CHARS:,} chars) "
        f"plus {len(skill()):,} chars of SKILL.md"
    )


if __name__ == "__main__":
    main()
