/* The control-plane client: sign-in, organizations, members, invites, tokens
 * and the region list.
 *
 * `gen/` is generated by `npm run generate` in `clients/typescript`, from
 * `openapi/control.json`, and is checked in — never edited by hand. It is NOT
 * published: the control API is internal, so it changes without SDK or
 * versioning obligations, which matters because regions, billing and the org
 * model are exactly the surfaces most likely to churn. Hand-maintaining these
 * 17 endpoints' request and response types here instead is the drift
 * `backend/services/user/tenants.py` exists to warn about.
 *
 * Two clients, not one client pointed at two hosts: this one always talks to
 * the control plane, and `lib/api.ts`'s always talks to one region.
 */

import { createClient, createConfig } from "./gen/client";
import { TalqingControlApi } from "./gen";

export type {
  AuthContextResponse,
  InviteRequest,
  InviteResponse,
  McpTokenResponse,
  MemberResponse,
  OrgResponse,
  PatchOrgRequest,
  RegionResponse,
  RoleRequest,
  TokenCreatedResponse,
  TokenResponse,
} from "./gen";

/* Control is one host for the whole deployment, so unlike the regional base URL
 * this really is a build-time constant. Bundlers inline `NEXT_PUBLIC_*`, so a
 * missing value cannot be caught at runtime — fail the build instead. */
const CONTROL_URL = process.env.NEXT_PUBLIC_CONTROL_API_URL;
if (!CONTROL_URL) {
  throw new Error("NEXT_PUBLIC_CONTROL_API_URL is not set (see frontend/README.md)");
}

const LOGIN_PATH = "/login";

const http = createClient(
  createConfig({
    baseUrl: CONTROL_URL.replace(/\/+$/, ""),
    throwOnError: true,
    responseStyle: "data",
    // The session cookie is issued by control with `domain=talqing.com`, so it
    // reaches both this host and the region's.
    credentials: "include",
  }),
);

/* Same shape as the regional client's: the transport throws the parsed error
 * body, which is a plain object with no status and no stack. Wrapping it here is
 * what makes `catch (e)` see a real Error, and lets one place notice that a
 * session is over. */
http.interceptors.error.use((error, response) => {
  if (!response) return error;
  const failure = new ControlApiError(error as { detail?: { message?: string } }, response);
  if (failure.status === 401 && typeof window !== "undefined") {
    if (window.location.pathname !== LOGIN_PATH) window.location.replace(LOGIN_PATH);
  }
  return failure;
});

export class ControlApiError extends Error {
  readonly status: number;
  readonly errors: string[];

  constructor(body: { detail?: { message?: string; errors?: string[] } }, response: Response) {
    super(body?.detail?.message || `Request failed with ${response.status}`);
    this.name = "ControlApiError";
    this.status = response.status;
    this.errors = body?.detail?.errors ?? [];
  }
}

/**
 * Every generated method, with the `| undefined` that `throwOnError` makes
 * impossible removed.
 *
 * The generator emits `<ThrowOnError extends boolean = false>` on every method,
 * so a client configured to throw still returns `T | undefined` at the type
 * level and every call site would need a `!`. There is no setting for it. The
 * published SDK re-types its tree the same way, for the same reason.
 *
 * `Exclude<R, undefined>` rather than `NonNullable<R>`: the latter turns the
 * `void` of a 204 into `{}`. `...args: infer A` keeps each method's
 * optional-argument arity, so `orgs.list()` with no argument still compiles.
 */
type Throwing<T> = {
  [K in keyof T]: T[K] extends (...args: infer A) => Promise<infer R>
    ? (...args: A) => Promise<Exclude<R, undefined>>
    : Throwing<T[K]>;
};

export const control = new TalqingControlApi({ client: http }) as Throwing<TalqingControlApi>;

/** Where to send the browser to start Google sign-in.
 *
 *  `google/start` is a control route, so this lives here rather than on the
 *  published SDK — the one method that would otherwise make that client span
 *  two planes. `country` is the visitor's ISO 3166-1 alpha-2 code, read off
 *  Cloudflare's edge, and it decides which region their FIRST workspace is
 *  created in. Omitted when unknown, which is a normal outcome. */
export function googleLoginUrl(country?: string | null): string {
  const url = new URL(`${CONTROL_URL!.replace(/\/+$/, "")}/v1/auth/google/start`);
  if (country) url.searchParams.set("country", country);
  return url.toString();
}
