/* The second half of `npm run generate`.
 *
 * The package's own semver moves with the SDK; the API it was generated against
 * moves on its own. A support conversation needs both, so the spec's
 * `info.version` is emitted beside the rest of the generated tree — where
 * `generate:check` already guards it against drift. hey-api does not emit it. */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const spec = JSON.parse(
  readFileSync(new URL("../../../../../openapi/openapi.json", import.meta.url), "utf8"),
);

writeFileSync(
  fileURLToPath(new URL("../src/gen/apiVersion.ts", import.meta.url)),
  `// This file is auto-generated by scripts/api-version.mjs\n\n` +
    `/** The Talqing API version \`src/gen\` was generated against. */\n` +
    `export const API_VERSION = ${JSON.stringify(spec.info.version)};\n`,
);
